//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppFile()
        {
            this.DemandeAccesEngin = new HashSet<DemandeAccesEngin>();
            this.ResultatControleEntete = new HashSet<ResultatControleEntete>();
        }
    
        public long AppFileId { get; set; }
        public string SourceName { get; set; }
        public string SourceId { get; set; }
        public string ContainerName { get; set; }
        public string OriginalFileName { get; set; }
        public string SystemFileName { get; set; }
        public long FileSize { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeAccesEngin> DemandeAccesEngin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatControleEntete> ResultatControleEntete { get; set; }
    }
}
