//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeAccesEngin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemandeAccesEngin()
        {
            this.DemandeResultatEntete = new HashSet<DemandeResultatEntete>();
            this.ReponseDemande = new HashSet<ReponseDemande>();
            this.ResultatInfoGenerale = new HashSet<ResultatInfoGenerale>();
        }
    
        public long Id { get; set; }
        public long TypeCheckListId { get; set; }
        public string Observation { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public long TypeEnginId { get; set; }
        public long EntityId { get; set; }
        public bool Autorise { get; set; }
        public System.DateTime DatePlannification { get; set; }
        public Nullable<long> NatureMatiereId { get; set; }
        public Nullable<long> AppFileId { get; set; }
        public Nullable<long> StatutDemandeId { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
    
        public virtual AppFiles AppFiles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Entities Entities { get; set; }
        public virtual REF_NatureMatiere REF_NatureMatiere { get; set; }
        public virtual REF_StatutDemandes REF_StatutDemandes { get; set; }
        public virtual REF_TypeCheckList REF_TypeCheckList { get; set; }
        public virtual REF_TypeEngin REF_TypeEngin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemandeResultatEntete> DemandeResultatEntete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReponseDemande> ReponseDemande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatInfoGenerale> ResultatInfoGenerale { get; set; }
    }
}
