//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeResultatEntete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemandeResultatEntete()
        {
            this.ResultatExigence = new HashSet<ResultatExigence>();
        }
    
        public long Id { get; set; }
        public long DemandeAccesEnginId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> AppFileId { get; set; }
    
        public virtual AppFiles AppFiles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual DemandeAccesEngin DemandeAccesEngin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatExigence> ResultatExigence { get; set; }
    }
}
