//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEnginEntities : DbContext
    {
        public TestEnginEntities()
            : base("name=TestEnginEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppFiles> AppFiles { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<DemandeAccesEngin> DemandeAccesEngin { get; set; }
        public virtual DbSet<DemandeResultatEntete> DemandeResultatEntete { get; set; }
        public virtual DbSet<Entities> Entities { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<REF_CheckListExigence> REF_CheckListExigence { get; set; }
        public virtual DbSet<REF_CheckListRubrique> REF_CheckListRubrique { get; set; }
        public virtual DbSet<REF_InfoGenerale> REF_InfoGenerale { get; set; }
        public virtual DbSet<REF_InfoGeneralRubrique> REF_InfoGeneralRubrique { get; set; }
        public virtual DbSet<REF_MailingList> REF_MailingList { get; set; }
        public virtual DbSet<REF_NatureMatiere> REF_NatureMatiere { get; set; }
        public virtual DbSet<REF_StatutDemandes> REF_StatutDemandes { get; set; }
        public virtual DbSet<REF_TypeCheckList> REF_TypeCheckList { get; set; }
        public virtual DbSet<REF_TypeEngin> REF_TypeEngin { get; set; }
        public virtual DbSet<ReponseDemande> ReponseDemande { get; set; }
        public virtual DbSet<ResultatExigence> ResultatExigence { get; set; }
        public virtual DbSet<ResultatInfoGenerale> ResultatInfoGenerale { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
    }
}
