//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_CheckListExigence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REF_CheckListExigence()
        {
            this.ResultatExigence = new HashSet<ResultatExigence>();
        }
    
        public long Id { get; set; }
        public long CheckListRubriqueId { get; set; }
        public string Name { get; set; }
        public int ShowOrder { get; set; }
        public bool IsActif { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsHasDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual REF_CheckListRubrique REF_CheckListRubrique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatExigence> ResultatExigence { get; set; }
    }
}
