//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_InfoGenerale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REF_InfoGenerale()
        {
            this.ResultatInfoGenerale = new HashSet<ResultatInfoGenerale>();
            this.REF_TypeCheckList = new HashSet<REF_TypeCheckList>();
        }
    
        public long Id { get; set; }
        public long InfoGeneralRubriqueId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual REF_InfoGeneralRubrique REF_InfoGeneralRubrique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultatInfoGenerale> ResultatInfoGenerale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REF_TypeCheckList> REF_TypeCheckList { get; set; }
    }
}
