//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatInfoGenerale
    {
        public long Id { get; set; }
        public long DemandeAccesEnginId { get; set; }
        public long InfoGeneraleId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ValueInfo { get; set; }
    
        public virtual DemandeAccesEngin DemandeAccesEngin { get; set; }
        public virtual REF_InfoGenerale REF_InfoGenerale { get; set; }
    }
}
