//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatExigence
    {
        public long Id { get; set; }
        public long CheckListExigenceId { get; set; }
        public bool IsConform { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Observation { get; set; }
        public long DemandeResultatEnteteId { get; set; }
    
        public virtual DemandeResultatEntete DemandeResultatEntete { get; set; }
        public virtual REF_CheckListExigence REF_CheckListExigence { get; set; }
    }
}
